rejstore/projectrejstore/cart/urls.py
from . import views
from django.urls import path


app_name='cart'
urlpatterns = [
    path('add/<int:product_id>/', views.add_cart, name='add_cart'),
    path('', views.cart_detail, name='cart_detail'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
    path('full_remove/<int:product_id>/', views.full_remove, name='full_remove'),
]

rejstore/projectrejstore/projectrejstore/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('shop/', include('rej_home.urls')),
    path('search/', include('search_app.urls')),
    path('cart/', include('cart.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rejstore/projectrejstore/rej_home/urls.py
from . import views
from django.urls import path

app_name = 'rej_home'
urlpatterns = [
    path('', views.allProducts, name='allProducts'),
    path('<slug:category_slug>/', views.allProducts, name='products_by_category'),
    path('<slug:category_slug>/<slug:product_slug>/', views.productDetails, name='productDetails'),
]

rejstore/projectrejstore/search_app/urls.py
from . import views
from django.urls import path


app_name = 'search_app'
urlpatterns = [
    path('', views.searchResult, name='searchResult'),
]

rejstore/projectrejstore/cart/models.py
from django.db import models
from rej_home.models import Product


class Cart(models.Model):
    cart_id = models.CharField(max_length=250, blank=True)
    date_added = models.DateField(auto_now_add=True)

    class Meta:

        db_table = 'Cart'
        ordering  = ['date_added']

    def __str__(self):
        return '{}'.format(self.cart_id)


class CartItems(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    active = models.BooleanField(default=True)

    class Meta:
        db_table = 'CartItem'

    def sub_total(self):
        return self.product.productPrice * self.quantity

    def __str__(self):
        return '{}'.format(self.product)

rejstore/projectrejstore/rej_home/models.py
from django.db import models
from django.urls import reverse


class Category(models.Model):
    categoryName = models.CharField(max_length=300, unique=True)
    slug = models.SlugField(max_length=300, unique=True)
    categoryImage = models.ImageField(upload_to='category_img', blank=True)
    categoryDescription = models.TextField(blank=True)

    class Meta:
        ordering = ('categoryName',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def get_url(self):
        return reverse('rej_home:products_by_category', args=[self.slug])

    def __str__(self):
        return '{}'.format(self.categoryName)


class Product(models.Model):
    productName = models.CharField(max_length=300, unique=True)
    slug = models.SlugField(max_length=300, unique=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    productImage = models.ImageField(upload_to='category_img', blank=True)
    productDescription = models.TextField(blank=True)
    productPrice = models.DecimalField(max_digits=20, decimal_places=2)
    productAvailable = models.BooleanField(default=True)
    productStock = models.IntegerField()
    productCreatedAt = models.DateField(auto_now_add=True)
    productUpdatedAt = models.DateField(auto_now=True)

    class Meta:
        ordering = ('productName',)
        verbose_name = 'product'
        verbose_name_plural = 'products'

    def get_url(self):
        return reverse('rej_home:productDetails', args=[self.category.slug, self.slug])

    def __str__(self):
        return '{}'.format(self.productName)

rejstore/projectrejstore/search_app/models.py
from django.db import models

# Create your models here.

rejstore/projectrejstore/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from rej_home.models import Product
from .models import Cart,CartItems
from django.core.exceptions import ObjectDoesNotExist


def _cart_id(request):
    cart = request.session.session_key
    if not cart:
        cart = request.session.create()
    return cart


def add_cart(request, product_id):
    product = Product.objects.get(id=product_id)
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
    except Cart.DoesNotExist:
        cart = Cart.objects.create(
            cart_id=_cart_id(request)
        )
        cart.save(),
    try:
        cart_item = CartItems.objects.get(product=product, cart=cart)
        if cart_item.quantity < cart_item.product.productStock:
            cart_item.quantity += 1
        cart_item.save()
    except CartItems.DoesNotExist:
        cart_item = CartItems.objects.create(
            product=product,
            quantity=1,
            cart=cart,
        )
        cart_item.save()
    return redirect('cart:cart_detail')


def cart_detail(request, total=0, counter=0, cart_items=None):
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
        cart_items = CartItems.objects.filter(cart=cart, active=True)
        for cart_item in cart_items:
            total += (cart_item.product.productPrice * cart_item.quantity)
            counter += cart_item.quantity
    except ObjectDoesNotExist:
        pass
    return render(request, 'cart.html', dict(cart_items=cart_items, total=total, counter=counter))


def cart_remove(request, product_id):
    cart = Cart.objects.get(cart_id=_cart_id(request))
    product = get_object_or_404(Product, id=product_id)
    cart_item = CartItems.objects.get(product=product, cart=cart)
    if cart_item.quantity > 1:
        cart_item.quantity -= 1
        cart_item.save()
    else:
        cart_item.delete()
    return redirect('cart:cart_detail')


def full_remove(request, product_id):
    cart = Cart.objects.get(cart_id=_cart_id(request))
    product = get_object_or_404(Product, id=product_id)
    cart_item = CartItems.objects.get(product=product, cart=cart)
    cart_item.delete()
    return redirect('cart:cart_detail')

rejstore/projectrejstore/rej_home/views.py
from django.shortcuts import render, get_object_or_404
from . models import Category, Product
from django.core.paginator import Paginator, EmptyPage, InvalidPage


def allProducts(request, category_slug=None):
    categoryPage = None
    productList = None
    if category_slug != None:
        categoryPage = get_object_or_404(Category, slug=category_slug)
        productList = Product.objects.all().filter(category=categoryPage, productAvailable=True)
    else:
        productList = Product.objects.all().filter(productAvailable=True)
    paginator = Paginator(productList, 8)
    try:
        page = int(request.GET.get('page', '1'))
    except:
        page = 1
    try:
        products = paginator.page(page)
    except (EmptyPage, InvalidPage):
        products = paginator.page(paginator.num_pages)
    return render(request, 'allProduct.html', {'categoryObj': categoryPage, 'products': products})


def productDetails(request, category_slug, product_slug):
    try:
        product = Product.objects.get(category__slug=category_slug, slug=product_slug)
    except Exception as e:
        raise e
    return render(request, 'productDetails.html', {'product': product})

rejstore/projectrejstore/search_app/views.py
from django.shortcuts import render
from django.db.models import Q
from rej_home.models import Product


def searchResult(request):
    products = None
    query = None
    if 'q' in request.GET:
        query = request.GET.get('q')
        products = Product.objects.all().filter(Q(productName__contains=query) | Q(productDescription__contains=query))
    return render(request, 'search.html', {'query': query, 'products': products})

rejstore/projectrejstore/templates/allProduct.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
  {% if categoryObj %}
     {{ categoryObj.categoryDescription|truncatewords:155 }}
  {% else %}
     Rej Store
  {% endif %}
{% endblock %}

{% block title %}
  {% if categoryObj %}
     {{ categoryObj.categoryName }}
  {% else %}
     Rej Store
  {% endif %}
{% endblock %}

{% block content %}
   {% if categoryObj %}
      <div class="container">
          <div class="row mx-auto">
              <img class="category_banner" src="{{categoryObj.categoryImage.url}}" alt="{{categoryObj.categoryName}}">
          </div>
      </div>
   {% else %}
      <div class="container">
          <div class="row mx-auto">
              <img class="all_product_banner" src="{% static 'img/banner/raj_banner.png' %}" alt="rejbanner">
          </div>
          <div>
              <div>
                  <div>
                      <h1 class="text-center our_products_collections_title">Our Products Collections</h1>
                      <p class="text-justify our_products_collections_p">Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of "de Finibus Bonorum et Malorum" (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, "Lorem ipsum dolor sit amet..", comes from a line in section 1.10.32.Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of "de Finibus Bonorum et Malorum" (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, "Lorem ipsum dolor sit amet..", comes from a line in section 1.10.32.</p>
                  </div>
              </div>
          </div>
      </div>
   {% endif %}
   <div class="container all_product_container">
       <div class="row mx-auto text-center all_product_row">
           {% for product in products %}
             <div class="row card_product_col col-9 col-sm-6 col-md-3 xol-lg-3">
                 <div class="card" style="width: 18rem;">
                    <a href="{{product.get_url}}"><img src="{{product.productImage.url}}" class="card_all_product" alt="{{product.productName}}"></a>
                    <div class="card-body">
                      <p class="card-text card_product_name">{{product.productName}}</p>
                    </div>
                 </div>
             </div>
           {% endfor %}
       </div>
       <div class="pagination_section">
           {% if products.paginator.num_pages > 1 %}
              <div class="text-center page_num">
                  {% for pg in products.paginator.page_range %}
                     <a href="?page={{pg}}" class="btn btn-light btn-sm {% if products.number == pg %} active {% endif %}">{{pg}}</a>
                  {% endfor %}
              </div>
           {% endif %}
       </div>
   </div>
{% endblock %}

rejstore/projectrejstore/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="{% block metadescription %} {% endblock %}">
    <link href="{% static 'css/custom.css/' %}" rel="stylesheet">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <title>{% block title %} {% endblock %}</title>
</head>
<body>
    {% include 'header.html' %}
    {% include 'navbar.html' %}

    {% block content %}
    {% endblock %}

    {% include 'footer.html' %}

    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="https://kit.fontawesome.com/a076d05399.js"></script>
</body>
</html>

rejstore/projectrejstore/templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    This is cart page. Proceed to review your items and place the order
{% endblock %}

{% block title %}
     Cart - R virtual shop
{% endblock %}

{% block content %}
   {% if not cart_items %}
       <div>
         <div class="text-center">
           <br>
           <h1 class="text-center my_title"> Your Shopping Cart is Empty</h1>
           <br>
           <p class="text-center empty_cart_para">
             Please click <a class="custom_a" href="{% url 'rej_home:allProducts' %}"> here To </a> continue shopping
           </p>
         </div>
       </div>
   {% else %}
       <div>
         <div class="text-center">
           <br>
           <h1 class="text-center my_title"> Your Shopping Cart </h1>
           <br>
         </div>
         <div class="row mx-auto">
            <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
              <table class="table my_custom_table">
                <thead class="my_custom_thead">
                   <tr>
                     <th colspan="5">
                       Your Items
                     </th>
                   </tr>
                </thead>
                <tbody>
                  {% for cart_item in cart_items %}
                    <tr class="my_td">
                      <td>
                          <a href="cart_item.product.get_absolute_url"><img src="{{cart_item.product.productImage.url}}" alt="" class="float-left rounded custom_image"></a>
                      </td>
                      <td class="text-left">
                          {{cart_item.product.productName}}
                          <br>
                          SKU : {{cart_item.product.id}}
                          <br>
                          Price : $ {{cart_item.product.productPrice}}
                          <br>
                          Quantity : {{cart_item.quantity}} x $ {{cart_item.product.productPrice}}
                      </td>
                      <td>
                          $ {{cart_item.sub_total}}
                      </td>
                      {% if cart_item.quantity < cart_item.product.productStock %}
                        <td>
                            <a href="{% url 'cart:add_cart' cart_item.product.id %} " class="custom_a"> <i class="fa fa-plus custom_icon"></i></a>
                           &nbsp;<a href="{% url 'cart:cart_remove' cart_item.product.id %}" class="custom_a"><i class="fa fa-minus custom_icon"></i></a>
                           &nbsp;<a href="{% url 'cart:full_remove' cart_item.product.id %}" class="custom_icon"><i class="fa fa-trash custom_icon"></i></a>
                        </td>
                      {% else %}
                         <td>
                            &nbsp;<a href="{% url 'cart:cart_remove' cart_item.product.id %}" class="custom_a"><i class="fa fa-minus custom_icon"></i></a>
                            &nbsp;<a href="{% url 'cart:full_remove' cart_item.product.id %}" class="custom_icon"><i class="fa fa-trash custom_icon"></i></a>
                        </td>
                      {% endif %}
                    </tr>
                 {% endfor %}
                </tbody>
              </table>
            </div>
            <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
              <table class="table my_custom_table">
                  <thead class="my_custom_thead">
                     <tr>
                        <th>
                           Checkout
                        </th>
                     </tr>
                  </thead>
                  <tbody>
                    <tr>
                      <td>
                          Please review your shopping cart items before proceeding with the order payment.
                      </td>
                    </tr>
                    <tr>
                        <td class="text-left">
                            Your Total is : <strong> {{ total }} </strong>
                        </td>
                    </tr>
                  </tbody>
              </table>
              <div class="mx-auto">
                  <a href="{% url 'rej_home:allProducts' %}" class="btn btn-secondary btn-block my_custom_button">Continue shopping</a>
                  <a href="{% url 'rej_home:allProducts' %}" class="btn btn-secondary btn-block my_custom_button">Make Payment</a>
              </div>
            </div>
         </div>
       </div>
   {% endif %}
{% endblock %}

rejstore/projectrejstore/templates/footer.html
{% load static %}
<div class="container foot_container my-5">
  <div class="navbar-fixed-bottom footer_div">
    <footer class="text-center text-lg-start text-white main_footer">
      <div class="container p-4 pb-0">
      <section class="">
        <div class="row">
          <div class="col-md-3 col-lg-3 col-xl-3 mx-auto mt-3">
            <h6 class="text-uppercase mb-4 font-weight-bold">
              Rej Store
            </h6>
            <p>
              Here you can use rows and columns to organize your footer
              content. Lorem ipsum dolor sit amet, consectetur adipisicing
              elit.
            </p>
          </div>
          <hr class="w-100 clearfix d-md-none" />
          <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mt-3">
            <h6 class="text-uppercase mb-4 font-weight-bold">Products</h6>
            <p>
              <a class="text-white">MDBootstrap</a>
            </p>
            <p>
              <a class="text-white">MDWordPress</a>
            </p>
            <p>
              <a class="text-white">BrandFlow</a>
            </p>
            <p>
              <a class="text-white">Bootstrap Angular</a>
            </p>
          </div>

          <hr class="w-100 clearfix d-md-none" />
          <hr class="w-100 clearfix d-md-none" />

          <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mt-3">
            <h6 class="text-uppercase mb-4 font-weight-bold">Contact</h6>
            <p><i class="fas fa-home mr-3"></i> New York, NY 10012, US</p>
            <p><i class="fas fa-envelope mr-3"></i> info@gmail.com</p>
            <p><i class="fas fa-phone mr-3"></i> + 01 234 567 88</p>
            <p><i class="fas fa-print mr-3"></i> + 01 234 567 89</p>
          </div>

          <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mt-3">
            <h6 class="text-uppercase mb-4 font-weight-bold">Follow us</h6>
            <a class="btn btn-primary btn-floating m-1" style="background-color: #3b5998" href="#!" role="button"><i class="fab fa-facebook-f"></i></a>
            <a class="btn btn-primary btn-floating m-1" style="background-color: #55acee" href="#!" role="button"><i class="fab fa-twitter"></i></a>
            <a class="btn btn-primary btn-floating m-1" style="background-color: #dd4b39" href="#!" role="button"><i class="fab fa-google"></i></a>
            <a class="btn btn-primary btn-floating m-1" style="background-color: #ac2bac" href="#!" role="button"><i class="fab fa-instagram"></i></a>
            <a class="btn btn-primary btn-floating m-1" style="background-color: #0082ca" href="#!" role="button"><i class="fab fa-linkedin-in"></i></a>
            <a class="btn btn-primary btn-floating m-1" style="background-color: #333333" href="#!" role="button"><i class="fab fa-github"></i></a>
          </div>
        </div>
      </section>
    </div>
    <div class="text-center p-3 footer_p_3">
      © 2020 Copyright:
      <a class="text-white" href="https://mdbootstrap.com/">rejstore.com</a>
    </div>
  </footer>
 </div>
</div>

rejstore/projectrejstore/templates/header.html
{% load static %}

<div class="logo_header_img_div">
  <a href=""><img class="logo_header_img" src="{% static 'img/logo/rej_shop.png' %}" alt="Rej Store"></a>
</div>

rejstore/projectrejstore/templates/navbar.html
{% load static %}
<nav class="navbar navbar-custom navbar-dark bg-light navbar-expand-lg">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'rej_home:allProducts' %}">
      Rej Store
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'rej_home:allProducts' %}">Home</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Shop
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
               <li><a class="dropdown-item" href="{% url 'rej_home:allProducts' %}">All products</a></li>
            {% for categoryLink in links %}
               <li><a class="dropdown-item" href="{{categoryLink.get_url}}">{{categoryLink.categoryName}}</a></li>
            {% endfor %}
          </ul>
        </li>
          <li class="nav-item">
             <a class="nav-link" href=""><i class="fa fa-shopping-cart"></i></a>
          </li>
      </ul>
      <form class="d-flex" action="{% url 'search_app:searchResult' %}" method="get">
        <input class="form-control me-2" type="search" placeholder="Search" name="q" aria-label="Search">
        <button class="btn btn-outline-success" type="submit"><i class="fa fa-search"></i></button>
      </form>
    </div>
  </div>
</nav>

rejstore/projectrejstore/templates/productDetails.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    {{ product.productDescription|truncatewords:155 }}
{% endblock %}

{% block title %}
    {% if categoryObj %}
      {{ product.productName }}
    {% endif %}
{% endblock %}
{% block content %}
    <div class="container">
        <div>
            <p><a href="{% url 'rej_home:allProducts' %}">Home</a> | <a href="{{product.category.get_url}}">{{product.category}}</a> | {{product.productName}}</p>
        </div>
    </div>
<div class="container">
    <div class="row">
        <div class="col-12 col-sm-12 col-md-12 col-lg-6">
            <div>
                <div style="min-width: 18rem;" class="prod_detail_pic_div">
                  <img class="product_detail_pic" src="{{product.productImage.url}}" alt="{{product.productName}}">
                </div>
            </div>
        </div>
        <div class="col-12 col-sm-12 col-md-12 col-lg-6">
            <div>
                <h1>{{product.productName}}</h1>
                <h2 class="prod_detail_head">Product Description</h2>
                <p class="text-justify">{{product.productDescription}}</p>
                {% if product.productStock <= 0 %}
                    <p><b>OUT OF STOCK</b></p>
                {% else %}
                    <a href="" class="btn btn-info">Add To Cart</a>
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

rejstore/projectrejstore/templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
   We have plenty of options for you
{% endblock %}

{% block title %}
  {% if categoryObj %}
     search
  {% endif %}
{% endblock %}

{% block content %}
  <div class="container">
      <div>
          <p class="text-center searched_for">You have searched for <b>"{{query}}"</b></p>
      </div>
      <div class="row mx-auto">
          {% for product in products %}
          <div class="col-9 col-sm-6 col-md-3 xol-lg-3">
              <div class="card" style="width: 18rem;">
                  <a href="{{product.get_url}}"><img src="{{product.productImage.url}}" class="card_all_product" alt="{{product.productName}}"></a>
                  <div class="card-body">
                      <h5>{{product.productName}}</h5>
                      <h5>{{product.productPrice}}</h5>
                  </div>
              </div>
          </div>
          {% empty %}
          <div>
              <p class="text-center"> 0 results found</p>
          </div>
          {% endfor %}
      </div>
  </div>

{% endblock %}